### PR TITLE
Added "partialsExtension" option

### PR DESCRIPTION
**Pull request by dudabone**

### CODE REVIEW

**Comment by kirbysayshi** [comment]
Hi @dudabone,

Thanks for the contribution, but I'm not sure I see how this is useful. If you wanted multiple extensions, or even support for only the `.java` extension you can configure that at the transform level already: https://github.com/epeli/node-hbsfy#custom-extension.

But maybe I'm misunderstanding your approach here?

**Comment by dudabone** [comment]
Hi kirbysayshi,

What I meant to support here is quite different than what custom extensions support. Some libraries support declaring partials without specifying the extension. E.g, in your template you can declare:
{{>path/to/partial}}

Instead of:
{{>path/to/partial.hbs}}

I have encountered this need because I am using handlebars.java to render templates on the server, and it supports this functionality (see the suffix option). In order to reuse these templates in JS, I needed the same support in hbsfy, when using the traverse option.

I must say though, after revisiting my code that it still requires some minor changes (e.g I did not add tests). So, if I was able to convince you that this option is worth adding, please let me know and I will continue working on it.

**Comment by kirbysayshi** [comment]
Ok, I think I understand now. I'm wondering if you can solve this with one of two options:

1) Preprocess your templates using a regex as part of some build step. Search for `([a-zA-z0-9_])\s?}}` and replace it with `$1.java }}`.

2) Write a very small browserify transform to append the file extension for you. This is greatly simplified with the [browserify-transform-tools](https://www.npmjs.com/package/browserify-transform-tools#creating-a-require-transform), which has a factory function well-designed for this task.

I'm willing to include this functionality, but with the following constraints:

- no `baseDir` option. the path within the `{{> }}` should map directly to the file system, with no differences from how node itself would handle paths. Any time the base path is configurable it adds a level of complication to maintenance that I'm not willing to take on: the transform now has to somehow infer what the user meant without a lot of hints. The node_modules resolution algo is well-defined, and I don't want to deviate from that. Plus, how would configurable extensions work if `traverse` is `false`, and we're relying on handlebars' internal template cache?

- the most simple logic possible: basically "if no extension is attached to the partial, add a custom one if the custom one was defined".

**Comment by kirbysayshi** [comment]
Sorry for any discrepancies in the above message and an email notification, I accidentally mashed the "Comment" button before I was finished! :stuck_out_tongue_winking_eye:

**Comment by kirbysayshi** [comment]
I'm going to close this for now, feel free to reopen if you decide to update the PR.

**Pull request closed without merging**
